version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Run linter
          command: npx vue-cli-service lint
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build and minify app
          command: yarn build
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build